version: '3.8'

services:
  db:
    image: postgres:15
    container_name: railsathi_db
    environment:
      POSTGRES_DB: rail_sathi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d railsathi"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: railsathi_web
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/railsathi
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload   

volumes:
  postgres_data: